alias vi=nvim
alias vim=nvim
alias ls='gls --color'
alias ll='ls -lFa'
alias cdg='cd $(git root)'
alias cddf='cd ${DOTFILES_REPOSITORY_ROOT}'
alias cdw='cd ${HOME}/Workspace'
alias szrc='source $HOME/.zshrc'
alias tmux='tmux -2'
alias psql='/Library/PostgreSQL/12/bin/psql'
